name: Java CI with Maven

on:
  push:

permissions:
  contents: write 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: badges
        generate-branches-badge: true
        generate-summary: true

    - name: Commit and push badges
      if: github.event_name == 'push'
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Update badges'
        add: 'badges/*.svg'
